### ISSUE TITLE
From Text demo's domain file is still using version 2

### ISSUE THREAD

**Issue by Hongbo-Miao** [RasaHQ/rasa-3.x-form-examples#2]
From Text demo's domain file is still using version 2.
It would be great to upgrade to version 3, thanks! 😃

https://github.com/RasaHQ/rasa-3.x-form-examples/blob/138c660756aa841a301175fa4b8fbb73802fb024/04-from-text/domain.yml#L1

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
It's been a month since I made the project, but they should all work in Rasa 3.0 as well. I agree though that the version numbers should be updated.

**Comment by Hongbo-Miao** [comment]
Thanks @koaning ! Just tested, it does work.
I added the from based this repo in a domain.yml which is using version 3.
It would be great to have one official form demo that always up-to-date! As I thought there might a breaking change even for domain.yml

**Comment by koaning** [comment]
Just fixes the domain files. 

It's hard for us to maintain a repo for forms that's always consistent when features for forms also change over time. That's why I figured that a demo repo per major Rasa version would be a good thing.
